name = "html-hub"
main = "worker.js"
compatibility_date = "2025-05-01"

[[kv_namespaces]]
binding = "FILE_HUB"
id = "dbcc16e231c54aceb7682ccd5f22c997"

[[env.production.kv_namespaces]]
binding = "FILE_HUB"
id = "dbcc16e231c54aceb7682ccd5f22c997"
